#ifndef IIMODMANLIB_GLOBAL_H
#define IIMODMANLIB_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(IIMODMANLIB_STATIC)
#  define IIMODMANLIBSHARED_EXPORT
#elif defined(IIMODMANLIB_LIBRARY)
#  define IIMODMANLIBSHARED_EXPORT Q_DECL_EXPORT
#else
#  define IIMODMANLIBSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // IIMODMANLIB_GLOBAL_H
